#!/usr/bin/env python3
"""il2cpp_index.py — build a compact name->RVA index from an Il2CppDumper
script.json so code can resolve il2cpp API names at runtime.

Outputs (base name defaults to `il2cpp_index`):
  <base>.h    C header: sorted (FNV-1a64 hash, u32 RVA) arrays for methods and
              fields. Compile into a program and use lxgr_il2cpp_method().
  <base>.bin  binary index for runtime file loading (lxgr_il2cpp_method_file()):
              "LX2I" + u32 n_methods + u32 n_fields, then for methods then
              fields: n*(u64 hash) followed by n*(u32 rva), each block sorted
              by hash.

Usage:
  il2cpp_index.py <script.json> [out_base]
"""

import json
import struct
import sys


def fnv1a64(s):
    h = 0xCBF29CE484222325
    for b in s.encode("utf-8", "replace"):
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def build(entries):
    seen = set()
    rows = []
    for name, addr in entries:
        if not name or addr <= 0:
            continue
        h = fnv1a64(name)
        if h in seen:
            continue
        seen.add(h)
        rows.append((h, addr & 0xFFFFFFFF))
    rows.sort(key=lambda r: r[0])
    return rows


def emit_header(rows, name, fp):
    fp.write("/* generated by il2cpp_index.py — do not edit */\n")
    fp.write("#define LXGR_IL2CPP_INDEX_%s %d\n" % (name.upper(), len(rows)))
    fp.write("static const uint64_t lxgr_il2cpp_index_%s_hash[LXGR_IL2CPP_INDEX_%s] = {\n"
             % (name, name.upper()))
    for i in range(0, len(rows), 6):
        fp.write("    " + ", ".join("0x%016xULL" % r[0] for r in rows[i:i + 6]) + ",\n")
    fp.write("};\n")
    fp.write("static const uint32_t lxgr_il2cpp_index_%s_rva[LXGR_IL2CPP_INDEX_%s] = {\n"
             % (name, name.upper()))
    for i in range(0, len(rows), 12):
        fp.write("    " + ", ".join("0x%08xU" % (r[1] & 0xFFFFFFFF) for r in rows[i:i + 12]) + ",\n")
    fp.write("};\n\n")


def emit_bin(rows, fp):
    for h, _ in rows:
        fp.write(struct.pack("<Q", h))
    for _, rva in rows:
        fp.write(struct.pack("<I", rva))


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    src = sys.argv[1]
    base = sys.argv[2] if len(sys.argv) > 2 else "il2cpp_index"
    d = json.load(open(src))
    methods = build((m["Name"], m["Address"]) for m in d.get("ScriptMethod", []))
    fields = build((m["Name"], m["Address"]) for m in d.get("ScriptMetadata", []))
    print("methods=%d fields=%d" % (len(methods), len(fields)))

    with open(base + ".h", "w") as f:
        f.write("/* il2cpp_index.h — generated by il2cpp_index.py; do not edit */\n")
        f.write("#ifndef IL2CPP_INDEX_H\n#define IL2CPP_INDEX_H\n")
        f.write("#include <stdint.h>\n\n")
        emit_header(methods, "methods", f)
        emit_header(fields, "fields", f)
        f.write("#endif\n")

    with open(base + ".bin", "wb") as f:
        f.write(b"LX2I")
        f.write(struct.pack("<II", len(methods), len(fields)))
        emit_bin(methods, f)
        emit_bin(fields, f)
    print("wrote %s.h (%d bytes) and %s.bin" % (base, len(open(base + ".h", "rb").read()), base))
    return 0


if __name__ == "__main__":
    sys.exit(main())
